#!/usr/bin/env python3
"""Stand-in for authselect below a scratch root (tests/fingerprint-lid-install-test.sh).

Usage: authselect-stub.py ROOT COMMAND ...

Supports what install/fingerprint-lid.sh uses: current --raw, check,
create-profile NAME -b BASE [--symlink-*], test PROFILE FEATURES --system-auth,
select PROFILE FEATURES [-q] [--backup=NAME]. Profiles live in
ROOT/usr/share/authselect/default/NAME and ROOT/etc/authselect/custom/NAME;
templates are rendered with the directives the Fedora "local" profile uses in
system-auth. Every call is appended to ROOT/authselect-calls.log. A file
ROOT/authselect-fail-select makes select fail; ROOT/authselect-fail-check makes
check fail.
"""
import re
import shutil
import sys
from pathlib import Path

HEADER = (
    "# Generated by authselect\n"
    "# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.\n"
    "# You can stop authselect from managing your configuration by calling 'authselect opt-out'.\n"
    "# See authselect(8) for more details.\n\n"
)
DIRECTIVE = re.compile(r"\{(include|exclude) if \"([^\"]+)\"\}")
INLINE = re.compile(r"\{if (not )?\"([^\"]+)\":([^}|]*)(?:\|([^}]*))?\}")


def profile_dir(root, profile):
    if profile.startswith("custom/"):
        return root / "etc/authselect/custom" / profile[len("custom/"):]
    return root / "usr/share/authselect/default" / profile


def render(template, features):
    lines = []
    for line in template.splitlines():
        keep = True
        for kind, feature in DIRECTIVE.findall(line):
            enabled = feature in features
            keep = keep and (enabled if kind == "include" else not enabled)
        if not keep:
            continue
        line = DIRECTIVE.sub("", line)

        def inline(match):
            negate, feature, yes, no = match.groups()
            enabled = (feature in features) != bool(negate)
            return yes if enabled else (no or "")

        line = INLINE.sub(inline, line)
        lines.append(line.rstrip())
    return "\n".join(lines) + "\n"


def parse_profile_args(args):
    positional = [arg for arg in args if not arg.startswith("-")]
    return positional[0], positional[1:]


def main():
    root = Path(sys.argv[1])
    args = sys.argv[2:]
    with open(root / "authselect-calls.log", "a") as log:
        log.write(" ".join(args) + "\n")
    conf = root / "etc/authselect/authselect.conf"
    command = args[0] if args else ""

    if command == "current":
        if not conf.exists():
            print("No existing configuration detected.")
            return 2
        words = conf.read_text().split()
        print(" ".join(words))
        return 0
    if command == "check":
        return 1 if (root / "authselect-fail-check").exists() else 0
    if command == "create-profile":
        name = args[1]
        base = args[args.index("-b") + 1]
        source = profile_dir(root, base)
        target = root / "etc/authselect/custom" / name
        if not source.is_dir() or target.exists():
            print("create-profile failed", file=sys.stderr)
            return 1
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, target)
        return 0
    if command == "test":
        profile, features = parse_profile_args(args[1:])
        template = profile_dir(root, profile) / "system-auth"
        if not template.exists():
            return 1
        print("File /etc/pam.d/system-auth:")
        print(render(template.read_text(), features) + "\n\n", end="")
        return 0
    if command == "select":
        if (root / "authselect-fail-select").exists():
            return 1
        profile, features = parse_profile_args(args[1:])
        template = profile_dir(root, profile) / "system-auth"
        if not template.exists():
            return 1
        conf.parent.mkdir(parents=True, exist_ok=True)
        (root / "etc/authselect/system-auth").write_text(HEADER + render(template.read_text(), features))
        conf.write_text("\n".join([profile] + features) + "\n")
        return 0
    print(f"unsupported: {args}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
