#!/usr/bin/env python3
"""Build config/emoji.json for the emoji picker from the CLDR annotations.

Run once when the emoji list should be refreshed:

    scripts/build-emoji-data.py            write config/emoji.json
    scripts/build-emoji-data.py --check    say what would change, write nothing

The result is checked in, so the shell needs neither this script nor the
cldr-emoji-annotation package at runtime.

What counts as an emoji is Unicode's own answer
(/usr/share/unicode/ucd/emoji/emoji-data.txt, Emoji_Presentation): CLDR also
annotates braces, digits and mathematical signs, and those are characters, not
emoji. The names and the search words then come from CLDR
(/usr/share/unicode/cldr/common/annotations/en.xml).

The groups are ours: CLDR has none, and the file that carries them
(emoji-test.txt) is not packaged on Fedora, so they are the code point ranges
below. Anything outside them lands in Symbols, which is where a picker looks
for a character it cannot place anyway.

Skin tones are left out on purpose: the picker applies the one the user chose
to whichever emoji supports it, so listing six copies of every hand would make
the list six times longer for no gain.
"""

import argparse
import json
import pathlib
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
ANNOTATIONS = pathlib.Path("/usr/share/unicode/cldr/common/annotations/en.xml")
# The country flags and the skin-tone variants are generated by CLDR rather
# than written by hand, so they live in a second file. The flags are wanted,
# the skin tones are not (see above).
DERIVED = pathlib.Path("/usr/share/unicode/cldr/common/annotationsDerived/en.xml")
TARGET = ROOT / "config" / "emoji.json"
VERSION = 1

# (first, last, group) over the first code point, in the order they are tried.
RANGES = [
    (0x1F3FB, 0x1F3FF, "skip"),
    (0x1F600, 0x1F64F, "smileys"),
    (0x1F910, 0x1F92F, "smileys"),
    (0x1F970, 0x1F97A, "smileys"),
    (0x1FAE0, 0x1FAEF, "smileys"),
    (0x1F464, 0x1F487, "people"),
    (0x1F44A, 0x1F450, "people"),
    (0x1F574, 0x1F596, "people"),
    (0x1F930, 0x1F93A, "people"),
    (0x1F9B0, 0x1F9DF, "people"),
    (0x1FAF0, 0x1FAFF, "people"),
    (0x1F400, 0x1F43F, "nature"),
    (0x1F980, 0x1F9AE, "nature"),
    (0x1F330, 0x1F335, "nature"),
    (0x1F337, 0x1F34E, "nature"),
    (0x1F32D, 0x1F32F, "food"),
    (0x1F34F, 0x1F37F, "food"),
    (0x1F950, 0x1F96F, "food"),
    (0x1F3A0, 0x1F3CA, "activities"),
    (0x1F3CF, 0x1F3D3, "activities"),
    (0x1F93B, 0x1F94F, "activities"),
    (0x1F380, 0x1F397, "activities"),
    (0x1F3C5, 0x1F3CE, "activities"),
    (0x1F680, 0x1F6C5, "travel"),
    (0x1F30D, 0x1F320, "travel"),
    (0x1F3E0, 0x1F3F0, "travel"),
    (0x1F6D0, 0x1F6FF, "travel"),
    (0x1F4A1, 0x1F4FF, "objects"),
    (0x1F5A5, 0x1F5FF, "objects"),
    (0x1F9EA, 0x1F9FF, "objects"),
    (0x1FA70, 0x1FADF, "objects"),
    (0x1F1E6, 0x1F1FF, "flags"),
    (0x1F3F3, 0x1F3F4, "flags"),
]

GROUPS = [
    {"key": "recent", "label": "Recent", "icon": "\U0001F552"},
    {"key": "smileys", "label": "Smileys", "icon": "\U0001F600"},
    {"key": "people", "label": "People", "icon": "\U0001F44B"},
    {"key": "nature", "label": "Nature", "icon": "\U0001F436"},
    {"key": "food", "label": "Food", "icon": "\U0001F34E"},
    {"key": "activities", "label": "Activities", "icon": "\U000026BD"},
    {"key": "travel", "label": "Travel", "icon": "\U00002708"},
    {"key": "objects", "label": "Objects", "icon": "\U0001F4A1"},
    {"key": "symbols", "label": "Symbols", "icon": "\U00002764"},
    {"key": "flags", "label": "Flags", "icon": "\U0001F3F3"},
]

SKIN_TONES = set(range(0x1F3FB, 0x1F400))


def group_of(text):
    first = ord(text[0])
    for low, high, name in RANGES:
        if low <= first <= high:
            return name
    return "symbols"


EMOJI_DATA = pathlib.Path("/usr/share/unicode/ucd/emoji/emoji-data.txt")


def property_set(path, name):
    """The code points with one property of emoji-data.txt."""
    found = set()
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        points, _, prop = line.partition(";")
        if prop.strip() != name:
            continue
        low, _, high = points.strip().partition("..")
        found.update(range(int(low, 16), int(high or low, 16) + 1))
    return found


def is_emoji(text, presentation):
    """CLDR annotates braces, digits and mathematical signs too."""
    if not text:
        return False
    if ord(text[0]) in presentation:
        return True
    # A sequence is an emoji when it is built from ones: a flag is two regional
    # indicators, a family is people joined with a zero-width joiner.
    return len(text) > 1 and any(ord(ch) in presentation for ch in text)


def read_annotations(path):
    node = ET.parse(path).getroot().find("annotations")
    rows = {}
    for entry in node:
        cp = entry.get("cp")
        if cp is None:
            continue
        rows.setdefault(cp, {})[entry.get("type") or "keywords"] = (entry.text or "").strip()
    return rows


def build(rows, presentation, tonable):
    emoji = []
    for text, fields in rows.items():
        if not is_emoji(text, presentation):
            continue
        if any(ord(ch) in SKIN_TONES for ch in text):
            continue
        group = group_of(text)
        if group == "skip":
            continue
        name = fields.get("tts", "").strip()
        if not name:
            continue
        words = [word.strip() for word in fields.get("keywords", "").split("|")]
        words = sorted({word for word in words if word and word != name})
        entry = {"e": text, "n": name, "k": words, "g": group}
        # A skin tone is written after the emoji, but only where Unicode says
        # one belongs; the picker offers it for those and no others.
        if ord(text[0]) in tonable and len(text) == 1:
            entry["m"] = 1
        emoji.append(entry)
    order = {entry["key"]: index for index, entry in enumerate(GROUPS)}
    emoji.sort(key=lambda row: (order.get(row["g"], 99), row["n"]))
    return {"configVersion": VERSION, "groups": GROUPS, "emoji": emoji}


def main():
    parser = argparse.ArgumentParser(description="Build config/emoji.json from CLDR.")
    parser.add_argument("--check", action="store_true", help="report, write nothing")
    args = parser.parse_args()
    if not ANNOTATIONS.exists():
        print("missing %s (install cldr-emoji-annotation)" % ANNOTATIONS, file=sys.stderr)
        return 1
    if not EMOJI_DATA.exists():
        print("missing %s (install unicode-ucd)" % EMOJI_DATA, file=sys.stderr)
        return 1
    rows = read_annotations(ANNOTATIONS)
    if DERIVED.exists():
        for text, fields in read_annotations(DERIVED).items():
            rows.setdefault(text, fields)
    data = build(rows, property_set(EMOJI_DATA, "Emoji_Presentation"),
                 property_set(EMOJI_DATA, "Emoji_Modifier_Base"))
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n"
    counts = {}
    for row in data["emoji"]:
        counts[row["g"]] = counts.get(row["g"], 0) + 1
    tonable = sum(1 for row in data["emoji"] if row.get("m"))
    print("%d emoji, %d take a skin tone: %s"
          % (len(data["emoji"]), tonable,
             ", ".join("%s %d" % (key, counts.get(key, 0))
                       for key in (entry["key"] for entry in GROUPS) if key != "recent")))
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        print("unchanged" if current == text else "would change %s (%d bytes)" % (TARGET, len(text)))
        return 0
    TARGET.write_text(text)
    print("wrote %s (%d bytes)" % (TARGET, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
